use ccdb;

INSERT INTO country(id, country) VALUE ('1', 'Afghanistan');
INSERT INTO country(id, country) VALUE ('2', 'Albania');
INSERT INTO country(id, country) VALUE ('3', 'Algeria');
INSERT INTO country(id, country) VALUE ('4', 'American Samoa');
INSERT INTO country(id, country) VALUE ('5', 'Andorra');
INSERT INTO country(id, country) VALUE ('6', 'Angola');
INSERT INTO country(id, country) VALUE ('7', 'Anguilla');
INSERT INTO country(id, country) VALUE ('8', 'Antigua And Barbuda');
INSERT INTO country(id, country) VALUE ('9', 'Argentina');
INSERT INTO country(id, country) VALUE ('10', 'Armenia');
INSERT INTO country(id, country) VALUE ('11', 'Aruba');
INSERT INTO country(id, country) VALUE ('12', 'Australia');
INSERT INTO country(id, country) VALUE ('13', 'Austria');
INSERT INTO country(id, country) VALUE ('14', 'Azerbaijan');
INSERT INTO country(id, country) VALUE ('15', 'Bahrain');
INSERT INTO country(id, country) VALUE ('16', 'Bangladesh');
INSERT INTO country(id, country) VALUE ('17', 'Barbados');
INSERT INTO country(id, country) VALUE ('18', 'Belarus');
INSERT INTO country(id, country) VALUE ('19', 'Belgium');
INSERT INTO country(id, country) VALUE ('20', 'Belize');
INSERT INTO country(id, country) VALUE ('21', 'Benin');
INSERT INTO country(id, country) VALUE ('22', 'Bermuda');
INSERT INTO country(id, country) VALUE ('23', 'Bhutan');
INSERT INTO country(id, country) VALUE ('24', 'Bolivia');
INSERT INTO country(id, country) VALUE ('25', 'Bosnia And Herzegovina');
INSERT INTO country(id, country) VALUE ('26', 'Botswana');
INSERT INTO country(id, country) VALUE ('27', 'Brazil');
INSERT INTO country(id, country) VALUE ('28', 'British Virgin Islands');
INSERT INTO country(id, country) VALUE ('29', 'Brunei');
INSERT INTO country(id, country) VALUE ('30', 'Bulgaria');
INSERT INTO country(id, country) VALUE ('31', 'Burkina Faso');
INSERT INTO country(id, country) VALUE ('32', 'Burundi');
INSERT INTO country(id, country) VALUE ('33', 'Cabo Verde');
INSERT INTO country(id, country) VALUE ('34', 'Cambodia');
INSERT INTO country(id, country) VALUE ('35', 'Cameroon');
INSERT INTO country(id, country) VALUE ('36', 'Canada');
INSERT INTO country(id, country) VALUE ('37', 'Cayman Islands');
INSERT INTO country(id, country) VALUE ('38', 'Central African Republic');
INSERT INTO country(id, country) VALUE ('39', 'Chad');
INSERT INTO country(id, country) VALUE ('40', 'Chile');
INSERT INTO country(id, country) VALUE ('41', 'China');
INSERT INTO country(id, country) VALUE ('42', 'Christmas Island');
INSERT INTO country(id, country) VALUE ('43', 'Colombia');
INSERT INTO country(id, country) VALUE ('44', 'Comoros');
INSERT INTO country(id, country) VALUE ('45', 'Congo (Brazzaville)');
INSERT INTO country(id, country) VALUE ('46', 'Congo (Kinshasa)');
INSERT INTO country(id, country) VALUE ('47', 'Cook Islands');
INSERT INTO country(id, country) VALUE ('48', 'Costa Rica');
INSERT INTO country(id, country) VALUE ('49', 'Croatia');
INSERT INTO country(id, country) VALUE ('50', 'Cuba');
INSERT INTO country(id, country) VALUE ('51', 'Curaçao');
INSERT INTO country(id, country) VALUE ('52', 'Cyprus');
INSERT INTO country(id, country) VALUE ('53', 'Czechia');
INSERT INTO country(id, country) VALUE ('54', 'Côte dIvoire');
INSERT INTO country(id, country) VALUE ('55', 'Denmark');
INSERT INTO country(id, country) VALUE ('56', 'Djibouti');
INSERT INTO country(id, country) VALUE ('57', 'Dominica');
INSERT INTO country(id, country) VALUE ('58', 'Dominican Republic');
INSERT INTO country(id, country) VALUE ('59', 'Ecuador');
INSERT INTO country(id, country) VALUE ('60', 'Egypt');
INSERT INTO country(id, country) VALUE ('61', 'El Salvador');
INSERT INTO country(id, country) VALUE ('62', 'Equatorial Guinea');
INSERT INTO country(id, country) VALUE ('63', 'Eritrea');
INSERT INTO country(id, country) VALUE ('64', 'Estonia');
INSERT INTO country(id, country) VALUE ('65', 'Ethiopia');
INSERT INTO country(id, country) VALUE ('66', 'Falkland Islands (Islas Malvinas)');
INSERT INTO country(id, country) VALUE ('67', 'Faroe Islands');
INSERT INTO country(id, country) VALUE ('68', 'Federated States of Micronesia');
INSERT INTO country(id, country) VALUE ('69', 'Fiji');
INSERT INTO country(id, country) VALUE ('70', 'Finland');
INSERT INTO country(id, country) VALUE ('71', 'France');
INSERT INTO country(id, country) VALUE ('72', 'French Guiana');
INSERT INTO country(id, country) VALUE ('73', 'French Polynesia');
INSERT INTO country(id, country) VALUE ('74', 'Gabon');
INSERT INTO country(id, country) VALUE ('75', 'Gaza Strip');
INSERT INTO country(id, country) VALUE ('76', 'Georgia');
INSERT INTO country(id, country) VALUE ('77', 'Germany');
INSERT INTO country(id, country) VALUE ('78', 'Ghana');
INSERT INTO country(id, country) VALUE ('79', 'Gibraltar');
INSERT INTO country(id, country) VALUE ('80', 'Greece');
INSERT INTO country(id, country) VALUE ('81', 'Greenland');
INSERT INTO country(id, country) VALUE ('82', 'Grenada');
INSERT INTO country(id, country) VALUE ('83', 'Guadeloupe');
INSERT INTO country(id, country) VALUE ('84', 'Guam');
INSERT INTO country(id, country) VALUE ('85', 'Guatemala');
INSERT INTO country(id, country) VALUE ('86', 'Guinea');
INSERT INTO country(id, country) VALUE ('87', 'Guinea-Bissau');
INSERT INTO country(id, country) VALUE ('88', 'Guyana');
INSERT INTO country(id, country) VALUE ('89', 'Haiti');
INSERT INTO country(id, country) VALUE ('90', 'Honduras');
INSERT INTO country(id, country) VALUE ('91', 'Hong Kong');
INSERT INTO country(id, country) VALUE ('92', 'Hungary');
INSERT INTO country(id, country) VALUE ('93', 'Iceland');
INSERT INTO country(id, country) VALUE ('94', 'India');
INSERT INTO country(id, country) VALUE ('95', 'Indonesia');
INSERT INTO country(id, country) VALUE ('96', 'Iran');
INSERT INTO country(id, country) VALUE ('97', 'Iraq');
INSERT INTO country(id, country) VALUE ('98', 'Ireland');
INSERT INTO country(id, country) VALUE ('99', 'Isle Of Man');
INSERT INTO country(id, country) VALUE ('100', 'Israel');
INSERT INTO country(id, country) VALUE ('101', 'Italy');
INSERT INTO country(id, country) VALUE ('102', 'Jamaica');
INSERT INTO country(id, country) VALUE ('103', 'Japan');
INSERT INTO country(id, country) VALUE ('104', 'Jersey');
INSERT INTO country(id, country) VALUE ('105', 'Jordan');
INSERT INTO country(id, country) VALUE ('106', 'Kazakhstan');
INSERT INTO country(id, country) VALUE ('107', 'Kenya');
INSERT INTO country(id, country) VALUE ('108', 'Kiribati');
INSERT INTO country(id, country) VALUE ('109', 'Kosovo');
INSERT INTO country(id, country) VALUE ('110', 'Kuwait');
INSERT INTO country(id, country) VALUE ('111', 'Kyrgyzstan');
INSERT INTO country(id, country) VALUE ('112', 'Laos');
INSERT INTO country(id, country) VALUE ('113', 'Latvia');
INSERT INTO country(id, country) VALUE ('114', 'Lebanon');
INSERT INTO country(id, country) VALUE ('115', 'Lesotho');
INSERT INTO country(id, country) VALUE ('116', 'Liberia');
INSERT INTO country(id, country) VALUE ('117', 'Libya');
INSERT INTO country(id, country) VALUE ('118', 'Liechtenstein');
INSERT INTO country(id, country) VALUE ('119', 'Lithuania');
INSERT INTO country(id, country) VALUE ('120', 'Luxembourg');
INSERT INTO country(id, country) VALUE ('121', 'Macau');
INSERT INTO country(id, country) VALUE ('122', 'Macedonia');
INSERT INTO country(id, country) VALUE ('123', 'Madagascar');
INSERT INTO country(id, country) VALUE ('124', 'Malawi');
INSERT INTO country(id, country) VALUE ('125', 'Malaysia');
INSERT INTO country(id, country) VALUE ('126', 'Maldives');
INSERT INTO country(id, country) VALUE ('127', 'Mali');
INSERT INTO country(id, country) VALUE ('128', 'Malta');
INSERT INTO country(id, country) VALUE ('129', 'Marshall Islands');
INSERT INTO country(id, country) VALUE ('130', 'Martinique');
INSERT INTO country(id, country) VALUE ('131', 'Mauritania');
INSERT INTO country(id, country) VALUE ('132', 'Mauritius');
INSERT INTO country(id, country) VALUE ('133', 'Mayotte');
INSERT INTO country(id, country) VALUE ('134', 'Mexico');
INSERT INTO country(id, country) VALUE ('135', 'Moldova');
INSERT INTO country(id, country) VALUE ('136', 'Monaco');
INSERT INTO country(id, country) VALUE ('137', 'Mongolia');
INSERT INTO country(id, country) VALUE ('138', 'Montenegro');
INSERT INTO country(id, country) VALUE ('139', 'Montserrat');
INSERT INTO country(id, country) VALUE ('140', 'Morocco');
INSERT INTO country(id, country) VALUE ('141', 'Mozambique');
INSERT INTO country(id, country) VALUE ('142', 'Myanmar');
INSERT INTO country(id, country) VALUE ('143', 'Namibia');
INSERT INTO country(id, country) VALUE ('144', 'Nauru');
INSERT INTO country(id, country) VALUE ('145', 'Nepal');
INSERT INTO country(id, country) VALUE ('146', 'Netherlands');
INSERT INTO country(id, country) VALUE ('147', 'New Caledonia');
INSERT INTO country(id, country) VALUE ('148', 'New Zealand');
INSERT INTO country(id, country) VALUE ('149', 'Nicaragua');
INSERT INTO country(id, country) VALUE ('150', 'Niger');
INSERT INTO country(id, country) VALUE ('151', 'Nigeria');
INSERT INTO country(id, country) VALUE ('152', 'Niue');
INSERT INTO country(id, country) VALUE ('153', 'Norfolk Island');
INSERT INTO country(id, country) VALUE ('154', 'North Korea');
INSERT INTO country(id, country) VALUE ('155', 'Northern Mariana Islands');
INSERT INTO country(id, country) VALUE ('156', 'Norway');
INSERT INTO country(id, country) VALUE ('157', 'Oman');
INSERT INTO country(id, country) VALUE ('158', 'Pakistan');
INSERT INTO country(id, country) VALUE ('159', 'Palau');
INSERT INTO country(id, country) VALUE ('160', 'Panama');
INSERT INTO country(id, country) VALUE ('161', 'Papua New Guinea');
INSERT INTO country(id, country) VALUE ('162', 'Paraguay');
INSERT INTO country(id, country) VALUE ('163', 'Peru');
INSERT INTO country(id, country) VALUE ('164', 'Philippines');
INSERT INTO country(id, country) VALUE ('165', 'Pitcairn Islands');
INSERT INTO country(id, country) VALUE ('166', 'Poland');
INSERT INTO country(id, country) VALUE ('167', 'Portugal');
INSERT INTO country(id, country) VALUE ('168', 'Puerto Rico');
INSERT INTO country(id, country) VALUE ('169', 'Qatar');
INSERT INTO country(id, country) VALUE ('170', 'Reunion');
INSERT INTO country(id, country) VALUE ('171', 'Romania');
INSERT INTO country(id, country) VALUE ('172', 'Russia');
INSERT INTO country(id, country) VALUE ('173', 'Rwanda');
INSERT INTO country(id, country) VALUE ('174', 'Saint Barthelemy');
INSERT INTO country(id, country) VALUE ('175', 'Saint Helena, Ascension, And Tristan Da Cunha');
INSERT INTO country(id, country) VALUE ('176', 'Saint Kitts And Nevis');
INSERT INTO country(id, country) VALUE ('177', 'Saint Lucia');
INSERT INTO country(id, country) VALUE ('178', 'Saint Martin');
INSERT INTO country(id, country) VALUE ('179', 'Saint Pierre And Miquelon');
INSERT INTO country(id, country) VALUE ('180', 'Saint Vincent And The Grenadines');
INSERT INTO country(id, country) VALUE ('181', 'Samoa');
INSERT INTO country(id, country) VALUE ('182', 'San Marino');
INSERT INTO country(id, country) VALUE ('183', 'Sao Tome And Principe');
INSERT INTO country(id, country) VALUE ('184', 'Saudi Arabia');
INSERT INTO country(id, country) VALUE ('185', 'Senegal');
INSERT INTO country(id, country) VALUE ('186', 'Serbia');
INSERT INTO country(id, country) VALUE ('187', 'Seychelles');
INSERT INTO country(id, country) VALUE ('188', 'Sierra Leone');
INSERT INTO country(id, country) VALUE ('189', 'Singapore');
INSERT INTO country(id, country) VALUE ('190', 'Sint Maarten');
INSERT INTO country(id, country) VALUE ('191', 'Slovakia');
INSERT INTO country(id, country) VALUE ('192', 'Slovenia');
INSERT INTO country(id, country) VALUE ('193', 'Solomon Islands');
INSERT INTO country(id, country) VALUE ('194', 'Somalia');
INSERT INTO country(id, country) VALUE ('195', 'South Africa');
INSERT INTO country(id, country) VALUE ('196', 'South Georgia And South Sandwich Islands');
INSERT INTO country(id, country) VALUE ('197', 'South Korea');
INSERT INTO country(id, country) VALUE ('198', 'South Sudan');
INSERT INTO country(id, country) VALUE ('199', 'Spain');
INSERT INTO country(id, country) VALUE ('200', 'Sri Lanka');
INSERT INTO country(id, country) VALUE ('201', 'Sudan');
INSERT INTO country(id, country) VALUE ('202', 'Suriname');
INSERT INTO country(id, country) VALUE ('203', 'Svalbard');
INSERT INTO country(id, country) VALUE ('204', 'Swaziland');
INSERT INTO country(id, country) VALUE ('205', 'Sweden');
INSERT INTO country(id, country) VALUE ('206', 'Switzerland');
INSERT INTO country(id, country) VALUE ('207', 'Syria');
INSERT INTO country(id, country) VALUE ('208', 'Taiwan');
INSERT INTO country(id, country) VALUE ('209', 'Tajikistan');
INSERT INTO country(id, country) VALUE ('210', 'Tanzania');
INSERT INTO country(id, country) VALUE ('211', 'Thailand');
INSERT INTO country(id, country) VALUE ('212', 'The Bahamas');
INSERT INTO country(id, country) VALUE ('213', 'The Gambia');
INSERT INTO country(id, country) VALUE ('214', 'Timor-Leste');
INSERT INTO country(id, country) VALUE ('215', 'Togo');
INSERT INTO country(id, country) VALUE ('216', 'Tonga');
INSERT INTO country(id, country) VALUE ('217', 'Trinidad And Tobago');
INSERT INTO country(id, country) VALUE ('218', 'Tunisia');
INSERT INTO country(id, country) VALUE ('219', 'Turkey');
INSERT INTO country(id, country) VALUE ('220', 'Turkmenistan');
INSERT INTO country(id, country) VALUE ('221', 'Turks And Caicos Islands');
INSERT INTO country(id, country) VALUE ('222', 'Tuvalu');
INSERT INTO country(id, country) VALUE ('223', 'U.S. Virgin Islands');
INSERT INTO country(id, country) VALUE ('224', 'Uganda');
INSERT INTO country(id, country) VALUE ('225', 'Ukraine');
INSERT INTO country(id, country) VALUE ('226', 'United Arab Emirates');
INSERT INTO country(id, country) VALUE ('227', 'United Kingdom');
INSERT INTO country(id, country) VALUE ('228', 'United States');
INSERT INTO country(id, country) VALUE ('229', 'Uruguay');
INSERT INTO country(id, country) VALUE ('230', 'Uzbekistan');
INSERT INTO country(id, country) VALUE ('231', 'Vanuatu');
INSERT INTO country(id, country) VALUE ('232', 'Vatican City');
INSERT INTO country(id, country) VALUE ('233', 'Venezuela');
INSERT INTO country(id, country) VALUE ('234', 'Vietnam');
INSERT INTO country(id, country) VALUE ('235', 'Wallis And Futuna');
INSERT INTO country(id, country) VALUE ('236', 'West Bank');
INSERT INTO country(id, country) VALUE ('237', 'Yemen');
INSERT INTO country(id, country) VALUE ('238', 'Zambia');
INSERT INTO country(id, country) VALUE ('239', 'Zimbabwe');
